package com.github.arkadiusz97.discordmessagesllmmoderator.service.notifications;

import com.github.arkadiusz97.discordmessagesllmmoderator.model.PromptResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class EmailNotification implements Notification {

    private final JavaMailSender javaMailSender;
    private final String mailFrom;
    private final String mailTo;

    public EmailNotification(JavaMailSender javaMailSender, @Value("${spring.mail.username}") String mailFrom,
            @Value("${app.notifications.mail-to-address}") String mailTo) {
        this.javaMailSender = javaMailSender;
        this.mailFrom = mailFrom;
        this.mailTo = mailTo;
    }

    @Override
    public String name() {
        return "email";
    }

    @Override
    public void notify(Boolean removedMessage, PromptResponse promptResponse, String messageContent) {
        String messageContentToSend = getMessageContent(removedMessage, promptResponse, messageContent);
        log.debug("Sending mail to: {} with content: {}", mailTo, messageContentToSend);
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom(mailFrom);
        message.setTo(mailTo);
        message.setSubject("Received message, which breaks rules on your Discord server");
        message.setText(messageContentToSend);
        javaMailSender.send(message);
    }

    private String getMessageContent(Boolean removedMessage, PromptResponse promptResponse, String messageContent) {
        return "Received message '" +
                messageContent +
                "'\nIt breaks rule: '" +
                promptResponse.reasonForBreakingRules() +
                "'\nMessage will " +
                (removedMessage ? "be removed" : "not be removed") +
                ".\nIt is autogenerated message, please do not respond.";
    }

}
