package com.github.arkadiusz97.discordmessagesllmmoderator.service.notifications;

import com.github.arkadiusz97.discordmessagesllmmoderator.model.PromptResponse;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
public class EmailNotificationTest {

    @InjectMocks
    private EmailNotification emailNotification;

    @Mock
    private JavaMailSender javaMailSender;

    @ParameterizedTest
    @MethodSource("shouldNotifyData")
    public void shouldNotify(Boolean removedMessage) {
        String mailFrom = "mail from";
        String mailTo = "mail to";
        String messageContent = "message content";
        PromptResponse promptResponse = new PromptResponse(true, "reason");
        ReflectionTestUtils.setField(emailNotification,"mailFrom", mailFrom);
        ReflectionTestUtils.setField(emailNotification,"mailTo", mailTo);

        emailNotification.notify(removedMessage, promptResponse, messageContent);

        String messageContentToSend = "Received message '" +
                messageContent +
                "'\nIt breaks rule: '" +
                promptResponse.reasonForBreakingRules() +
                "'\nMessage will " +
                (removedMessage ? "be removed" : "not be removed") +
                ".\nIt is autogenerated message, please do not respond.";

        ArgumentCaptor<SimpleMailMessage> captor = ArgumentCaptor.forClass(SimpleMailMessage.class);
        verify(javaMailSender, times(1)).send(captor.capture());
        assertEquals(messageContentToSend, captor.getValue().getText());
    }

    @Test
    public void shouldReturnProperName() {
        assertEquals("email", emailNotification.name());
    }

    private static Stream<Arguments> shouldNotifyData() {
        return Stream.of(
                Arguments.of(false),
                Arguments.of(true)
        );
    }

}
